name = "NumericalEarth"
uuid = "904d977b-046a-4731-8b86-9235c0d1ef02"
license = "MIT"
version = "0.1.3"
authors = ["NumericalEarth contributors"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Breeze = "660aa2fb-d4c8-4359-a52c-9c057bc511da"
CFTime = "179af706-886a-5703-950a-314cd64e0468"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDA_Compiler_jll = "d1e2174e-dfdc-576e-b43e-73b79eb1aca8"
ClimaSeaIce = "6ba0ff68-24e6-4315-936c-2e99227c95a4"
CopernicusClimateDataStore = "bce3f73f-acea-4481-bd86-df89ecc2cb46"
CubicSplines = "9c784101-8907-5a6d-9be6-98f00873c89b"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
ImageMorphology = "787d08f9-d448-5407-9aad-5290dd7ab264"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MeshArrays = "cb8c808f-1acf-59a3-9d2b-6e38d009f683"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
SeawaterPolynomials = "d496a93d-167e-4197-9f49-d3af4ff8fe40"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Thermodynamics = "b60c26fb-14c3-4610-9d3e-2d17fe7ff00c"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[weakdeps]
CopernicusMarine = "cd43e856-93a3-40c8-bc9e-6146cdce14fa"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
SpeedyWeather = "9e226e20-d153-4fed-8a5b-493def4f21a9"
XESMF = "2e0b0046-e7a1-486f-88de-807ee8ffabe5"

[extensions]
NumericalEarthBreezeExt = "Breeze"
NumericalEarthCopernicusClimateDataStoreExt = "CopernicusClimateDataStore"
NumericalEarthCopernicusMarineExt = "CopernicusMarine"
NumericalEarthReactantExt = "Reactant"
NumericalEarthSpeedyWeatherExt = ["SpeedyWeather", "XESMF"]

[compat]
Adapt = "4"
Breeze = "0.3.3"
CFTime = "0.1, 0.2"
CUDA = "5.9.5"
CUDA_Compiler_jll = "v0.3.1"
ClimaSeaIce = "0.4.2, 0.5"
CopernicusClimateDataStore = "0.1"
CopernicusMarine = "0.1.1"
CubicSplines = "0.2"
DataDeps = "0.7"
DocStringExtensions = "0.9"
Downloads = "1.6"
Glob = "1"
ImageMorphology = "0.4"
JLD2 = "0.4, 0.5, 0.6"
KernelAbstractions = "0.9"
MPI = "0.20"
MeshArrays = "0.3, 0.4, 0.5"
NCDatasets = "0.12, 0.13, 0.14"
Oceananigans = "0.104.2, 0.105"
OffsetArrays = "1.14"
PrecompileTools = "1"
Reactant = "0.2.45"
Scratch = "1"
SeawaterPolynomials = "0.3.5"
SpeedyWeather = "0.17.4"
StaticArrays = "1"
Statistics = "1.9"
Thermodynamics = "0.15.3"
XESMF = "0.1.6"
ZipFile = "0.10"
julia = "1.10"

[extras]
Breeze = "660aa2fb-d4c8-4359-a52c-9c057bc511da"
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
CopernicusClimateDataStore = "bce3f73f-acea-4481-bd86-df89ecc2cb46"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Coverage", "Test", "MPIPreferences", "CUDA_Runtime_jll", "Reactant", "CopernicusClimateDataStore", "CopernicusMarine", "XESMF", "SpeedyWeather", "Breeze"]
